### PR TITLE
How to route a Resource with nested Route in Route Map of Discourse Plugin

### PR DESCRIPTION
**Pull request by ladydanger**
Hi @eviltrout 

We'd like to use resources in our route map - see here
https://github.com/team-melbourne-rgsoc2015/interface-testing/commit/2c15c6519ecdd7b345e4c231e80200725f6a5959#diff-6e09dc2d969db8b73c08fe571ef77675R5

But this isn't working.  We're unsure but is it something to do with this? https://github.com/discourse/discourse/blob/9ce66038647bc4ff63167fe9c74857a01acc0875/app/assets/javascripts/discourse/router.js.es6#L46-L48

Please help us put resources in route-map with your coding dojo :+1: 

Thanks mate!

### CODE REVIEW

**Comment by cyberkoi** [comment]
in addition to Vi's question above,
In Discourse, does there happen to be a shortcut to implement showModel() or a popup model dialog in _plugins_? We've been trying to emulate pre-existing popup models within the core, to no avail.

Hoping for something that works similar to meta-discourse's `keyboard shortcuts`?

(Quite ambitious with the features thus the questions. Thanks for taking the time to reply @eviltrout!)

**Comment by eviltrout** [comment]
> We'd like to use resources in our route map

This shouldn't be a problem. If you define a resource like so:

`this.resource('adPlugin', { path: '/ad_plugin' }, function() {`

It should provide that path. Was it not? Have you tried the [Ember Inspector](https://chrome.google.com/webstore/detail/ember-inspector/bmdblncegkenkacieihfhpjfppoconhi?hl=en)? It adds an Ember tab to Chrome's developer tools, and in there you can see a list of your routes. Is the `adPlugin` resource not being added there?

> In Discourse, does there happen to be a shortcut to implement showModel() or a popup model dialog in plugins?

You shouldn't need to do anything special to use a modal in a plugin. If you copy and paste code from the front end to show a modal (you need to declare the same templates) it should work. Do you have an example where it's failing?

**Comment by cyberkoi** [comment]
Hi Robin @eviltrout ,

> It should provide that path. Was it not? Have you tried the Ember Inspector? It adds an Ember tab to Chrome's developer tools, and in there you can see a list of your routes. Is the adPlugin resource not being added there?

You're right!  The routes are there when the code below is in our route map (see code 1 + image 1).  But it doesn't display anything.  Is it because of the way it's routing?  So in code 2 and image 2 below, we used a route and the route is adminPlugins.ad-plugin.  Should code 1 have to route as adminPlugin.ad-plugin too?

**Code 1**

```
export default {
  resource: 'admin.adminPlugins',
  path: '/plugins',
  map() {
    this.resource('adPlugin', { path: '/ad_plugin' }, function() {
    this.route('dfp');
    this.route('adsense');
    });
  }
};
```

**Image 1**
screen shot 2015-08-21 at 12 12 07 pm

**Code 2**

```
export default {
  resource: 'admin.adminPlugins',
  path: '/plugins',
  map() {
    this.route('ad-plugin')
    //this.resource('adPlugin', { path: '/ad_plugin' }, function() {
    //this.route('dfp');
    //this.route('adsense');
    //});
  }
};
```

**Image 2**
screen shot 2015-08-21 at 12 11 25 pm

ps. Just for fun - do you know which one of us two is writing this - is it Sarah or Vi?

**Comment by cyberkoi** [comment]
Sorry @eviltrout,
I sent a premature comment.
We fixed it now with this code:

```
export default {
  resource: 'admin.adminPlugins',
  path: '/plugins',
  map() {
    this.resource('adminPlugins.ad-plugin', { path: '/ad_plugin' }, function() {
    });
  }
};
```

**Pull request closed without merging**
